### ISSUE TITLE
[ User Service ] Update User Reading Progress

### ISSUE THREAD

**Issue by KodyAnderson1** [CodeRidersUWF101/user-service#14]
## User Stories
As an authenticated user, I want to update my reading status for any book in my library so that I can track my progress.

## Description

Aggregate Endpoint: `/users/progress`.
Method: `PUT`
Request Body: `UserLibraryWithBookDetails`

Users Service Endpoint: `/users/progress`
Method: `PUT`
Request Body: `UserLibraryWithBookDetails`

## Acceptance Criteria

**Comment by KodyAnderson1** [comment]
Done

**Comment by peytonspellings** [comment]
There is PatchMapping instead of PutMapping for this part.
