### ISSUE TITLE
[ User Service ] User Library Endpoint

### ISSUE THREAD

**Issue by KodyAnderson1** [CodeRidersUWF101/user-service#4]
## Description
As a user, I want all the relevant information sent to the client so that when I navigate to my library, all information is there.

ENDPOINT: `{{URL}}/users/library`
METHOD: `GET` 

## Request Parameters
1. `clerk_id`: id of user to get library for

Example URL: `{{URL}}/users/library?clerk_id=12345`

## Response
Sample Response

```json
{
    "clerk_id": "string",
    "library": "GoogleBook[]"
}
```

## Acceptance Criteria
GIVEN a user logs in
WHEN the user is redirected from the login page
AND the Aggregate Service requests a user's book from `{{URL}}/users/library`
AND a method of `GET`
AND has a request parameter of `clerk_id` 
THEN the client service will return all relevant information.
(**NOTE**:  `{{URL}}/users/library?clerk_id=1234`)

GIVEN I am an authenticated user
WHEN I navigate to my library
AND the Aggregate Service requests a user's book from `{{URL}}/users/library` 
AND a method of `GET`
AND has a request paramater of `clerk_id`
THEN the client service will return all relevant information.
(**NOTE**:  `{{URL}}/users/library?clerk_id=1234`)

**Comment by KodyAnderson1** [comment]
Done

**Comment by peytonspellings** [comment]
Works with the User Endpoint.
Having issues with Aggregate.

**Comment by peytonspellings** [comment]
Postman Tests Done
